// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAroYR51CwGatJ7iazi9sYMH0MW6hgfDDg',
    appId: '1:624692030196:web:075e887138362a8bda4ca1',
    messagingSenderId: '624692030196',
    projectId: 'project-fdb4b65e-57ff-4b13-afc',
    authDomain: 'project-fdb4b65e-57ff-4b13-afc.firebaseapp.com',
    storageBucket: 'project-fdb4b65e-57ff-4b13-afc.firebasestorage.app',
    measurementId: 'G-HJ6HGF5QNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-pc5alOLxBYYbi3awIPfF3--pcqY1gtI',
    appId: '1:624692030196:android:3fbd922c8eba045bda4ca1',
    messagingSenderId: '624692030196',
    projectId: 'project-fdb4b65e-57ff-4b13-afc',
    storageBucket: 'project-fdb4b65e-57ff-4b13-afc.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaIFEbB7nOXaY4FZXwDvD8blIRQ1BLCrQ',
    appId: '1:624692030196:ios:b698f17d31ee5423da4ca1',
    messagingSenderId: '624692030196',
    projectId: 'project-fdb4b65e-57ff-4b13-afc',
    storageBucket: 'project-fdb4b65e-57ff-4b13-afc.firebasestorage.app',
    androidClientId: '624692030196-upsve91bbor90ip5f7ri5ci6n9dejtlq.apps.googleusercontent.com',
    iosClientId: '624692030196-b6pm2or2jsoh19n94elnfc4vmb7bii27.apps.googleusercontent.com',
    iosBundleId: 'com.example.labombaApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaIFEbB7nOXaY4FZXwDvD8blIRQ1BLCrQ',
    appId: '1:624692030196:ios:b698f17d31ee5423da4ca1',
    messagingSenderId: '624692030196',
    projectId: 'project-fdb4b65e-57ff-4b13-afc',
    storageBucket: 'project-fdb4b65e-57ff-4b13-afc.firebasestorage.app',
    androidClientId: '624692030196-upsve91bbor90ip5f7ri5ci6n9dejtlq.apps.googleusercontent.com',
    iosClientId: '624692030196-b6pm2or2jsoh19n94elnfc4vmb7bii27.apps.googleusercontent.com',
    iosBundleId: 'com.example.labombaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAroYR51CwGatJ7iazi9sYMH0MW6hgfDDg',
    appId: '1:624692030196:web:ce3283c24cae2287da4ca1',
    messagingSenderId: '624692030196',
    projectId: 'project-fdb4b65e-57ff-4b13-afc',
    authDomain: 'project-fdb4b65e-57ff-4b13-afc.firebaseapp.com',
    storageBucket: 'project-fdb4b65e-57ff-4b13-afc.firebasestorage.app',
    measurementId: 'G-NQGC4HSD7R',
  );
}
